### ISSUE TITLE
Nonexistant case printing in error message

### ISSUE THREAD

**Issue by Temperz87** [jsiek/deduce#12]
The code
```
theorem smallest_nat_zero: 
	all x:Nat. if x <= 0 then x = 0
proof
	arbitrary x:Nat
	suppose prem: x <= 0
	switch x {
		case zero {
			.
		}
		case suc(y) suppose same_thing: x = suc(y) {
			have less_zero: suc(y) <= 0 by rewrite same_thing in prem
			have zero_less: 0 < suc(y) 
				by definition {operator <, operator <=, operator <=}

			have equal_or_less: suc(y) < 0 or suc(y) = 0 
				by apply less_equal_implies_less_or_equal[suc(y)][0] to less_zero

			cases equal_or_less
			case y_l_zero: suc(y) < 0 {
				have contradiction: not (0 < suc(y)) 
					by apply less_implies_not_greater to y_l_zero
		
				conclude false
					by apply contradiction to zero_less
			}
			case y_eq_zero: suc(y) = 0 {
				have contradiction: not (0 = suc(y))
					by apply less_not_equal to zero_less
				?
			}
		}
	}
end
```

Produces the error message
```
dont-give-ind-advice.pf:20.4-32.5: case false
does not match alternative in goal:
suc(y) = 0
```
Which should not be happening, as there is no case false. Said message gets printed in line 989 of proof_checker.py I think either the line should read `if frm2 != frm`, as `red_frm2` isn't even in the same scope as where the if statement gets declared, or there is a problem with the reduce function and the environment somehow, but I'm really not sure as to where this comes from.

**Comment by jsiek** [comment]
The scoping is not a problem. Python has different scoping than what you think.
Nevertheless, this is still a problem. But it seems the solution is tricky.
The obvious fix breaks other things. I'm searching for a good solution...
