### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by HalflingHelper** [jsiek/deduce#40]
```
theorem blah : all x, y : bool. true
proof
  ?
end
```
When forgetting type annotations in forall, the parser doesn't complain, because of the var_list grammar rule not requiring type annotations. However, uniquify does complain, with the error `'NoneType' object has no attribute 'copy'`

I can think of two solutions, I think the one I like more is just updating the grammar to require type annotations in forall.

(PS: Here is varlist)
```
?var_list:                                         -> empty_binding
    | ident ":" type                               -> single_binding
    | ident ":" type "," var_list                  -> push_binding
    | ident "," var_list                           -> push_var
    | ident    
```

**Comment by HalflingHelper** [comment]
Adding this rule in `Deduce.lark` seems to fix the error for the lalr parser
```
?type_annot_list:                                  -> empty_binding
    | ident ":" type                               -> single_binding
    | ident ":" type "," var_list                  -> push_binding
    ```

**Comment by HalflingHelper** [comment]
Same problem exists for `arbitrary x, y : bool`

We could also say that the type distributes in, but I think that that is less clear, particularly if someone writes
`all x, y : Nat, w, z : bool.`

**Comment by jsiek** [comment]
I like your fix with `type_annot_list`.

**Comment by HalflingHelper** [comment]
Hype, I'll add that and open a PR.
Adding tests as well and whatnot

**Comment by HalflingHelper** [comment]
Ok, I'll add that to the rec desc parser as well then. Might be hard to add a test for it since parser inputs won't agree unfortunately.
