### ISSUE TITLE
Not seting infix in every case

### ISSUE THREAD

**Issue by HalflingHelper** [jsiek/deduce#45]
This converts the goal to
` sum(node(a, d)) = + a`,
because infix isn't set for the operator + that it substitutes I suppose.

Should be `a+ foldr(...)`

```
theorem foldr_eq_sum : all ls : List<Nat>. sum(ls) = foldr(ls, 0, operator +)
proof
  induction List<Nat>
  case empty {
    definition { foldr, sum }
  }
  case node(a, d) suppose IH {
    suffices ? by definition {foldr} 
    ?
  }
end
```

**Comment by jsiek** [comment]
It turns out having an `infix` flag attached to `Call` was wrong headed because substitution can turn a normal call into call to a prefix operator. I've removed the `infix` flag and replaced the printing logic so it dispatches on the rator.
